"""Vendor the LocalGPT UI fonts locally (offline-first).

Downloads Lato and EB Garamond from Google Fonts as woff2 files into
app/static/fonts/ and rewrites the @font-face CSS to local /static/fonts/ URLs
in app/static/css/fonts.css, so the UI never needs a network connection.

Usage:
    python scripts/download_fonts.py

Only the latin and latin-ext subsets are kept (LocalGPT is an English UI);
that keeps the download small. Both families are licensed under the SIL Open
Font License 1.1 -- see app/static/fonts/README.md.
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "app" / "static" / "fonts"
CSS_OUT = ROOT / "app" / "static" / "css" / "fonts.css"

API_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Lato:ital,wght@0,300;0,400;0,700;0,900;1,400;1,700"
    "&family=EB+Garamond:ital,wght@0,400..800;1,400..800"
    "&display=swap"
)
BROWSER_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)
KEEP_SUBSETS = {"latin", "latin-ext"}

BLOCK_RE = re.compile(
    r"(?:/\*\s*(?P<subset>[a-z\-]+)\s*\*/\s*)?"
    r"@font-face\s*\{(?P<body>[^}]*)\}",
    re.IGNORECASE,
)
URL_RE = re.compile(r"url\((?P<url>https://[^)]+\.woff2)\)")
FAMILY_RE = re.compile(r"font-family:\s*'(?P<family>[^']+)'")
STYLE_RE = re.compile(r"font-style:\s*(?P<style>\w+)")
WEIGHT_RE = re.compile(r"font-weight:\s*(?P<weight>[0-9 ]+)")


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": BROWSER_UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def main() -> int:
    FONT_DIR.mkdir(parents=True, exist_ok=True)

    css = fetch(API_URL).decode("utf-8")
    out_rules: list[str] = []
    seen: set[str] = set()

    for match in BLOCK_RE.finditer(css):
        subset = (match.group("subset") or "").strip()
        if subset not in KEEP_SUBSETS:
            continue

        body = match.group("body")
        url_match = URL_RE.search(body)
        family_match = FAMILY_RE.search(body)
        style_match = STYLE_RE.search(body)
        weight_match = WEIGHT_RE.search(body)
        if not (url_match and family_match and style_match and weight_match):
            continue

        family = family_match.group("family")
        style = style_match.group("style")
        weight = " ".join(weight_match.group("weight").split())
        slug = family.lower().replace(" ", "-")
        weight_slug = weight.replace(" ", "-")
        name = f"{slug}-{weight_slug}-{style}-{subset}.woff2"

        if name not in seen:
            data = fetch(url_match.group("url"))
            (FONT_DIR / name).write_bytes(data)
            seen.add(name)
            print(f"  downloaded {name} ({len(data)} bytes)")

        local_url = f"/static/fonts/{name}"
        local_body = URL_RE.sub(f"url({local_url})", body)
        local_body = re.sub(r"\n\s*\n", "\n", local_body.strip())
        comment = f"/* {family} {weight} {style} — {subset} */"
        out_rules.append(f"{comment}\n@font-face {{{local_body}\n}}")

    if not out_rules:
        print("No font-face rules matched; nothing written.")
        return 1

    header = (
        "/* LocalGPT UI fonts, vendored locally for offline use.\n"
        "   Generated by scripts/download_fonts.py -- do not edit by hand.\n"
        "   Source: Google Fonts (Lato, EB Garamond), SIL OFL 1.1. */\n\n"
    )
    CSS_OUT.write_text(header + "\n\n".join(out_rules) + "\n", encoding="utf-8")
    print(f"Wrote {CSS_OUT.relative_to(ROOT)} with {len(out_rules)} @font-face rules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
